=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.1
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WebhookApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WebhookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookApi' do
    it 'should create an instance of WebhookApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WebhookApi)
    end
  end

  # unit tests for webhook_count
  # 
  # Count registered webhooks on the store.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :entity The entity you want to filter webhooks by (e.g. order or product)
  # @option opts [String] :action The action you want to filter webhooks by (e.g. order or product)
  # @option opts [BOOLEAN] :active The webhook status you want to filter webhooks by
  # @return [InlineResponse2002]
  describe 'webhook_count test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_create
  # 
  # Create webhook on the store and subscribe to it.
  # @param entity Specify the entity that you want to enable webhooks for (e.g product, order, customer, category)
  # @param action Specify what action (event) will trigger the webhook (e.g add, delete, or update)
  # @param callback Callback where the webhook should send the POST request when the event occurs
  # @param [Hash] opts the optional parameters
  # @option opts [String] :label The name you give to the webhook
  # @option opts [String] :fields Fields the webhook should send
  # @option opts [BOOLEAN] :active Webhook status
  # @option opts [String] :store_id Defines store id where the webhook should be assigned
  # @return [InlineResponse200]
  describe 'webhook_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_delete
  # 
  # Delete registered webhook on the store.
  # @param id Webhook id
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2004]
  describe 'webhook_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_events
  # 
  # List all Webhooks that are available on this store.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2003]
  describe 'webhook_events test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_list
  # 
  # List registered webhook on the store.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :params Set this parameter in order to choose which entity fields you want to retrieve
  # @option opts [Integer] :start This parameter sets the number from which you want to get entities
  # @option opts [Integer] :count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250
  # @option opts [String] :entity The entity you want to filter webhooks by (e.g. order or product)
  # @option opts [String] :action The action you want to filter webhooks by (e.g. add, update, or delete)
  # @option opts [BOOLEAN] :active The webhook status you want to filter webhooks by
  # @option opts [String] :ids List of сomma-separated webhook ids
  # @return [InlineResponse2001]
  describe 'webhook_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhook_update
  # 
  # Update Webhooks parameters.
  # @param id Webhook id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :callback Callback where the webhook should send the POST request when the event occurs
  # @option opts [String] :label The name you give to the webhook
  # @option opts [String] :fields Fields the webhook should send
  # @option opts [BOOLEAN] :active Webhook status
  # @return [InlineResponse2005]
  describe 'webhook_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
