=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.1
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ProductPriceAdd
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductPriceAdd' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductPriceAdd.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductPriceAdd' do
    it 'should create an instance of ProductPriceAdd' do
      expect(@instance).to be_instance_of(SwaggerClient::ProductPriceAdd)
    end
  end
  describe 'test attribute "product_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "group_prices"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

