=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.1
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module SwaggerClient

  class CustomerAdd
    # Defines customer's email
    attr_accessor :email

    # Defines customer's first name
    attr_accessor :first_name

    # Defines customer's last name
    attr_accessor :last_name

    # Defines customer's unique password
    attr_accessor :password

    # Defines the group where the customer
    attr_accessor :group

    # Entity's date creation
    attr_accessor :created_time

    # Entity's date modification
    attr_accessor :modified_time

    # Specifies customer's login name
    attr_accessor :login

    # Defines customer's last login time
    attr_accessor :last_login

    # Defines customer's birthday
    attr_accessor :birth_day

    # Defines customer's status
    attr_accessor :status

    # Defines whether the newsletter subscription is available for the user
    attr_accessor :news_letter_subscription

    # Defines customer's gender
    attr_accessor :gender

    # Link to customer website
    attr_accessor :website

    # Defines customer's fax
    attr_accessor :fax

    # Defines customer's company
    attr_accessor :company

    # Defines customer's phone number
    attr_accessor :phone

    attr_accessor :address


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email' => :'email',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'password' => :'password',
        :'group' => :'group',
        :'created_time' => :'created_time',
        :'modified_time' => :'modified_time',
        :'login' => :'login',
        :'last_login' => :'last_login',
        :'birth_day' => :'birth_day',
        :'status' => :'status',
        :'news_letter_subscription' => :'news_letter_subscription',
        :'gender' => :'gender',
        :'website' => :'website',
        :'fax' => :'fax',
        :'company' => :'company',
        :'phone' => :'phone',
        :'address' => :'address'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'email' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'password' => :'String',
        :'group' => :'String',
        :'created_time' => :'String',
        :'modified_time' => :'String',
        :'login' => :'String',
        :'last_login' => :'String',
        :'birth_day' => :'String',
        :'status' => :'String',
        :'news_letter_subscription' => :'BOOLEAN',
        :'gender' => :'String',
        :'website' => :'String',
        :'fax' => :'String',
        :'company' => :'String',
        :'phone' => :'String',
        :'address' => :'Array<CustomerAddAddress>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.has_key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.has_key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.has_key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.has_key?(:'group')
        self.group = attributes[:'group']
      end

      if attributes.has_key?(:'created_time')
        self.created_time = attributes[:'created_time']
      end

      if attributes.has_key?(:'modified_time')
        self.modified_time = attributes[:'modified_time']
      end

      if attributes.has_key?(:'login')
        self.login = attributes[:'login']
      end

      if attributes.has_key?(:'last_login')
        self.last_login = attributes[:'last_login']
      end

      if attributes.has_key?(:'birth_day')
        self.birth_day = attributes[:'birth_day']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = "enabled"
      end

      if attributes.has_key?(:'news_letter_subscription')
        self.news_letter_subscription = attributes[:'news_letter_subscription']
      else
        self.news_letter_subscription = false
      end

      if attributes.has_key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.has_key?(:'website')
        self.website = attributes[:'website']
      end

      if attributes.has_key?(:'fax')
        self.fax = attributes[:'fax']
      end

      if attributes.has_key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.has_key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.has_key?(:'address')
        if (value = attributes[:'address']).is_a?(Array)
          self.address = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @email.nil?
        invalid_properties.push("invalid value for 'email', email cannot be nil.")
      end

      if @first_name.nil?
        invalid_properties.push("invalid value for 'first_name', first_name cannot be nil.")
      end

      if @last_name.nil?
        invalid_properties.push("invalid value for 'last_name', last_name cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @email.nil?
      return false if @first_name.nil?
      return false if @last_name.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email == o.email &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          password == o.password &&
          group == o.group &&
          created_time == o.created_time &&
          modified_time == o.modified_time &&
          login == o.login &&
          last_login == o.last_login &&
          birth_day == o.birth_day &&
          status == o.status &&
          news_letter_subscription == o.news_letter_subscription &&
          gender == o.gender &&
          website == o.website &&
          fax == o.fax &&
          company == o.company &&
          phone == o.phone &&
          address == o.address
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [email, first_name, last_name, password, group, created_time, modified_time, login, last_login, birth_day, status, news_letter_subscription, gender, website, fax, company, phone, address].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
