=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.1
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module SwaggerClient

  class OrderAdd
    # Defines the order id if it is supported by the cart
    attr_accessor :order_id

    # Defines store id where the order should be assigned
    attr_accessor :store_id

    # Defines order status.
    attr_accessor :order_status

    # Send notifications to customer after order was created
    attr_accessor :send_notifications

    # Notify admin when new order was created.
    attr_accessor :send_admin_notifications

    # Defines the customer specified by email for whom order has to be created
    attr_accessor :customer_email

    # Specifies billing first name
    attr_accessor :bill_first_name

    # Specifies billing last name
    attr_accessor :bill_last_name

    # Specifies first billing address
    attr_accessor :bill_address_1

    # Specifies billing city
    attr_accessor :bill_city

    # Specifies billing postcode
    attr_accessor :bill_postcode

    # Specifies billing state code
    attr_accessor :bill_state

    # Specifies billing country code
    attr_accessor :bill_country

    # Specifies shipping first name
    attr_accessor :shipp_first_name

    # Specifies shipping last name
    attr_accessor :shipp_last_name

    # Specifies first shipping address
    attr_accessor :shipp_address_1

    # Specifies shipping city
    attr_accessor :shipp_city

    # Specifies shipping postcode
    attr_accessor :shipp_postcode

    # Specifies shipping state code
    attr_accessor :shipp_state

    # Specifies shipping country code
    attr_accessor :shipp_country

    # Defines order's total price
    attr_accessor :total_price

    # Specifies an order creation date in format Y-m-d H:i:s
    attr_accessor :date

    # Defines order payment method.<br/>Setting order_payment_method on Shopify will also change financial_status field value to 'paid'
    attr_accessor :order_payment_method

    # Defines order shipping method
    attr_accessor :order_shipping_method

    # Currency code of order
    attr_accessor :currency

    # Specifies second billing address
    attr_accessor :bill_address_2

    # Specifies billing company
    attr_accessor :bill_company

    # Specifies billing phone
    attr_accessor :bill_phone

    # Specifies billing fax
    attr_accessor :bill_fax

    # Specifies order comment
    attr_accessor :comment

    # Specifies admin's order comment
    attr_accessor :admin_comment

    # Specifies customer's first name
    attr_accessor :customer_first_name

    # Specifies customer’s last name
    attr_accessor :customer_last_name

    # Specifies customer’s birthday
    attr_accessor :customer_birthday

    # Specifies customer’s fax
    attr_accessor :customer_fax

    # Specifies customer’s phone
    attr_accessor :customer_phone

    # Specifies second address line of a shipping street address
    attr_accessor :shipp_address_2

    # Specifies shipping company
    attr_accessor :shipp_company

    # Specifies shipping phone
    attr_accessor :shipp_phone

    # Specifies shipping fax
    attr_accessor :shipp_fax

    # Specifies order's  modification date
    attr_accessor :date_modified

    # Specifies order's  finished date
    attr_accessor :date_finished

    # Total price of all ordered products multiplied by their number, excluding tax, shipping price and discounts
    attr_accessor :subtotal_price

    # The value of tax cost for order
    attr_accessor :tax_price

    # Specifies order's shipping price
    attr_accessor :shipping_price

    # Specifies order's shipping price tax
    attr_accessor :shipping_tax

    # Specifies order's discount
    attr_accessor :discount

    # Specifies order's coupon discount
    attr_accessor :coupon_discount

    # Discounts for order with gift certificates
    attr_accessor :gift_certificate_discount

    # Create order with fulfillment status
    attr_accessor :fulfillment_status

    # Create order with financial status
    attr_accessor :financial_status

    # Defines total paid amount for the order
    attr_accessor :total_paid

    # Identifying the system used to generate the order
    attr_accessor :external_source

    # Order tags
    attr_accessor :tags

    # The behaviour to use when updating inventory.<hr><div style=\"font-style:normal\">Values description:<div style=\"margin-left: 2%; padding-top: 2%\"><div style=\"font-size:85%\"><b>bypass</b> = Do not claim inventory </br></br><b>decrement_ignoring_policy</b> = Ignore the product's </br> inventory policy and claim amounts</br></br><b>decrement_obeying_policy</b> =  Obey the product's </br> inventory policy.</br></br></div></div></div>
    attr_accessor :inventory_behaviour

    # Defines whether the invoice is created automatically along with the order
    attr_accessor :create_invoice

    attr_accessor :order_item


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'order_id' => :'order_id',
        :'store_id' => :'store_id',
        :'order_status' => :'order_status',
        :'send_notifications' => :'send_notifications',
        :'send_admin_notifications' => :'send_admin_notifications',
        :'customer_email' => :'customer_email',
        :'bill_first_name' => :'bill_first_name',
        :'bill_last_name' => :'bill_last_name',
        :'bill_address_1' => :'bill_address_1',
        :'bill_city' => :'bill_city',
        :'bill_postcode' => :'bill_postcode',
        :'bill_state' => :'bill_state',
        :'bill_country' => :'bill_country',
        :'shipp_first_name' => :'shipp_first_name',
        :'shipp_last_name' => :'shipp_last_name',
        :'shipp_address_1' => :'shipp_address_1',
        :'shipp_city' => :'shipp_city',
        :'shipp_postcode' => :'shipp_postcode',
        :'shipp_state' => :'shipp_state',
        :'shipp_country' => :'shipp_country',
        :'total_price' => :'total_price',
        :'date' => :'date',
        :'order_payment_method' => :'order_payment_method',
        :'order_shipping_method' => :'order_shipping_method',
        :'currency' => :'currency',
        :'bill_address_2' => :'bill_address_2',
        :'bill_company' => :'bill_company',
        :'bill_phone' => :'bill_phone',
        :'bill_fax' => :'bill_fax',
        :'comment' => :'comment',
        :'admin_comment' => :'admin_comment',
        :'customer_first_name' => :'customer_first_name',
        :'customer_last_name' => :'customer_last_name',
        :'customer_birthday' => :'customer_birthday',
        :'customer_fax' => :'customer_fax',
        :'customer_phone' => :'customer_phone',
        :'shipp_address_2' => :'shipp_address_2',
        :'shipp_company' => :'shipp_company',
        :'shipp_phone' => :'shipp_phone',
        :'shipp_fax' => :'shipp_fax',
        :'date_modified' => :'date_modified',
        :'date_finished' => :'date_finished',
        :'subtotal_price' => :'subtotal_price',
        :'tax_price' => :'tax_price',
        :'shipping_price' => :'shipping_price',
        :'shipping_tax' => :'shipping_tax',
        :'discount' => :'discount',
        :'coupon_discount' => :'coupon_discount',
        :'gift_certificate_discount' => :'gift_certificate_discount',
        :'fulfillment_status' => :'fulfillment_status',
        :'financial_status' => :'financial_status',
        :'total_paid' => :'total_paid',
        :'external_source' => :'external_source',
        :'tags' => :'tags',
        :'inventory_behaviour' => :'inventory_behaviour',
        :'create_invoice' => :'create_invoice',
        :'order_item' => :'order_item'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'order_id' => :'String',
        :'store_id' => :'String',
        :'order_status' => :'String',
        :'send_notifications' => :'BOOLEAN',
        :'send_admin_notifications' => :'BOOLEAN',
        :'customer_email' => :'String',
        :'bill_first_name' => :'String',
        :'bill_last_name' => :'String',
        :'bill_address_1' => :'String',
        :'bill_city' => :'String',
        :'bill_postcode' => :'String',
        :'bill_state' => :'String',
        :'bill_country' => :'String',
        :'shipp_first_name' => :'String',
        :'shipp_last_name' => :'String',
        :'shipp_address_1' => :'String',
        :'shipp_city' => :'String',
        :'shipp_postcode' => :'String',
        :'shipp_state' => :'String',
        :'shipp_country' => :'String',
        :'total_price' => :'Float',
        :'date' => :'String',
        :'order_payment_method' => :'String',
        :'order_shipping_method' => :'String',
        :'currency' => :'String',
        :'bill_address_2' => :'String',
        :'bill_company' => :'String',
        :'bill_phone' => :'String',
        :'bill_fax' => :'String',
        :'comment' => :'String',
        :'admin_comment' => :'String',
        :'customer_first_name' => :'String',
        :'customer_last_name' => :'String',
        :'customer_birthday' => :'String',
        :'customer_fax' => :'String',
        :'customer_phone' => :'String',
        :'shipp_address_2' => :'String',
        :'shipp_company' => :'String',
        :'shipp_phone' => :'String',
        :'shipp_fax' => :'String',
        :'date_modified' => :'String',
        :'date_finished' => :'String',
        :'subtotal_price' => :'Float',
        :'tax_price' => :'Float',
        :'shipping_price' => :'Float',
        :'shipping_tax' => :'Float',
        :'discount' => :'Float',
        :'coupon_discount' => :'Float',
        :'gift_certificate_discount' => :'Float',
        :'fulfillment_status' => :'String',
        :'financial_status' => :'String',
        :'total_paid' => :'Float',
        :'external_source' => :'String',
        :'tags' => :'String',
        :'inventory_behaviour' => :'String',
        :'create_invoice' => :'BOOLEAN',
        :'order_item' => :'Array<OrderAddOrderItem>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.has_key?(:'store_id')
        self.store_id = attributes[:'store_id']
      end

      if attributes.has_key?(:'order_status')
        self.order_status = attributes[:'order_status']
      end

      if attributes.has_key?(:'send_notifications')
        self.send_notifications = attributes[:'send_notifications']
      else
        self.send_notifications = false
      end

      if attributes.has_key?(:'send_admin_notifications')
        self.send_admin_notifications = attributes[:'send_admin_notifications']
      else
        self.send_admin_notifications = false
      end

      if attributes.has_key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.has_key?(:'bill_first_name')
        self.bill_first_name = attributes[:'bill_first_name']
      end

      if attributes.has_key?(:'bill_last_name')
        self.bill_last_name = attributes[:'bill_last_name']
      end

      if attributes.has_key?(:'bill_address_1')
        self.bill_address_1 = attributes[:'bill_address_1']
      end

      if attributes.has_key?(:'bill_city')
        self.bill_city = attributes[:'bill_city']
      end

      if attributes.has_key?(:'bill_postcode')
        self.bill_postcode = attributes[:'bill_postcode']
      end

      if attributes.has_key?(:'bill_state')
        self.bill_state = attributes[:'bill_state']
      end

      if attributes.has_key?(:'bill_country')
        self.bill_country = attributes[:'bill_country']
      end

      if attributes.has_key?(:'shipp_first_name')
        self.shipp_first_name = attributes[:'shipp_first_name']
      end

      if attributes.has_key?(:'shipp_last_name')
        self.shipp_last_name = attributes[:'shipp_last_name']
      end

      if attributes.has_key?(:'shipp_address_1')
        self.shipp_address_1 = attributes[:'shipp_address_1']
      end

      if attributes.has_key?(:'shipp_city')
        self.shipp_city = attributes[:'shipp_city']
      end

      if attributes.has_key?(:'shipp_postcode')
        self.shipp_postcode = attributes[:'shipp_postcode']
      end

      if attributes.has_key?(:'shipp_state')
        self.shipp_state = attributes[:'shipp_state']
      end

      if attributes.has_key?(:'shipp_country')
        self.shipp_country = attributes[:'shipp_country']
      end

      if attributes.has_key?(:'total_price')
        self.total_price = attributes[:'total_price']
      end

      if attributes.has_key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.has_key?(:'order_payment_method')
        self.order_payment_method = attributes[:'order_payment_method']
      end

      if attributes.has_key?(:'order_shipping_method')
        self.order_shipping_method = attributes[:'order_shipping_method']
      end

      if attributes.has_key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.has_key?(:'bill_address_2')
        self.bill_address_2 = attributes[:'bill_address_2']
      end

      if attributes.has_key?(:'bill_company')
        self.bill_company = attributes[:'bill_company']
      end

      if attributes.has_key?(:'bill_phone')
        self.bill_phone = attributes[:'bill_phone']
      end

      if attributes.has_key?(:'bill_fax')
        self.bill_fax = attributes[:'bill_fax']
      end

      if attributes.has_key?(:'comment')
        self.comment = attributes[:'comment']
      end

      if attributes.has_key?(:'admin_comment')
        self.admin_comment = attributes[:'admin_comment']
      end

      if attributes.has_key?(:'customer_first_name')
        self.customer_first_name = attributes[:'customer_first_name']
      end

      if attributes.has_key?(:'customer_last_name')
        self.customer_last_name = attributes[:'customer_last_name']
      end

      if attributes.has_key?(:'customer_birthday')
        self.customer_birthday = attributes[:'customer_birthday']
      end

      if attributes.has_key?(:'customer_fax')
        self.customer_fax = attributes[:'customer_fax']
      end

      if attributes.has_key?(:'customer_phone')
        self.customer_phone = attributes[:'customer_phone']
      end

      if attributes.has_key?(:'shipp_address_2')
        self.shipp_address_2 = attributes[:'shipp_address_2']
      end

      if attributes.has_key?(:'shipp_company')
        self.shipp_company = attributes[:'shipp_company']
      end

      if attributes.has_key?(:'shipp_phone')
        self.shipp_phone = attributes[:'shipp_phone']
      end

      if attributes.has_key?(:'shipp_fax')
        self.shipp_fax = attributes[:'shipp_fax']
      end

      if attributes.has_key?(:'date_modified')
        self.date_modified = attributes[:'date_modified']
      end

      if attributes.has_key?(:'date_finished')
        self.date_finished = attributes[:'date_finished']
      end

      if attributes.has_key?(:'subtotal_price')
        self.subtotal_price = attributes[:'subtotal_price']
      end

      if attributes.has_key?(:'tax_price')
        self.tax_price = attributes[:'tax_price']
      end

      if attributes.has_key?(:'shipping_price')
        self.shipping_price = attributes[:'shipping_price']
      end

      if attributes.has_key?(:'shipping_tax')
        self.shipping_tax = attributes[:'shipping_tax']
      end

      if attributes.has_key?(:'discount')
        self.discount = attributes[:'discount']
      end

      if attributes.has_key?(:'coupon_discount')
        self.coupon_discount = attributes[:'coupon_discount']
      end

      if attributes.has_key?(:'gift_certificate_discount')
        self.gift_certificate_discount = attributes[:'gift_certificate_discount']
      end

      if attributes.has_key?(:'fulfillment_status')
        self.fulfillment_status = attributes[:'fulfillment_status']
      end

      if attributes.has_key?(:'financial_status')
        self.financial_status = attributes[:'financial_status']
      end

      if attributes.has_key?(:'total_paid')
        self.total_paid = attributes[:'total_paid']
      end

      if attributes.has_key?(:'external_source')
        self.external_source = attributes[:'external_source']
      end

      if attributes.has_key?(:'tags')
        self.tags = attributes[:'tags']
      end

      if attributes.has_key?(:'inventory_behaviour')
        self.inventory_behaviour = attributes[:'inventory_behaviour']
      else
        self.inventory_behaviour = "bypass"
      end

      if attributes.has_key?(:'create_invoice')
        self.create_invoice = attributes[:'create_invoice']
      else
        self.create_invoice = false
      end

      if attributes.has_key?(:'order_item')
        if (value = attributes[:'order_item']).is_a?(Array)
          self.order_item = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @order_status.nil?
        invalid_properties.push("invalid value for 'order_status', order_status cannot be nil.")
      end

      if @customer_email.nil?
        invalid_properties.push("invalid value for 'customer_email', customer_email cannot be nil.")
      end

      if @bill_first_name.nil?
        invalid_properties.push("invalid value for 'bill_first_name', bill_first_name cannot be nil.")
      end

      if @bill_last_name.nil?
        invalid_properties.push("invalid value for 'bill_last_name', bill_last_name cannot be nil.")
      end

      if @bill_address_1.nil?
        invalid_properties.push("invalid value for 'bill_address_1', bill_address_1 cannot be nil.")
      end

      if @bill_city.nil?
        invalid_properties.push("invalid value for 'bill_city', bill_city cannot be nil.")
      end

      if @bill_postcode.nil?
        invalid_properties.push("invalid value for 'bill_postcode', bill_postcode cannot be nil.")
      end

      if @bill_state.nil?
        invalid_properties.push("invalid value for 'bill_state', bill_state cannot be nil.")
      end

      if @bill_country.nil?
        invalid_properties.push("invalid value for 'bill_country', bill_country cannot be nil.")
      end

      if @order_item.nil?
        invalid_properties.push("invalid value for 'order_item', order_item cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @order_status.nil?
      return false if @customer_email.nil?
      return false if @bill_first_name.nil?
      return false if @bill_last_name.nil?
      return false if @bill_address_1.nil?
      return false if @bill_city.nil?
      return false if @bill_postcode.nil?
      return false if @bill_state.nil?
      return false if @bill_country.nil?
      return false if @order_item.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          order_id == o.order_id &&
          store_id == o.store_id &&
          order_status == o.order_status &&
          send_notifications == o.send_notifications &&
          send_admin_notifications == o.send_admin_notifications &&
          customer_email == o.customer_email &&
          bill_first_name == o.bill_first_name &&
          bill_last_name == o.bill_last_name &&
          bill_address_1 == o.bill_address_1 &&
          bill_city == o.bill_city &&
          bill_postcode == o.bill_postcode &&
          bill_state == o.bill_state &&
          bill_country == o.bill_country &&
          shipp_first_name == o.shipp_first_name &&
          shipp_last_name == o.shipp_last_name &&
          shipp_address_1 == o.shipp_address_1 &&
          shipp_city == o.shipp_city &&
          shipp_postcode == o.shipp_postcode &&
          shipp_state == o.shipp_state &&
          shipp_country == o.shipp_country &&
          total_price == o.total_price &&
          date == o.date &&
          order_payment_method == o.order_payment_method &&
          order_shipping_method == o.order_shipping_method &&
          currency == o.currency &&
          bill_address_2 == o.bill_address_2 &&
          bill_company == o.bill_company &&
          bill_phone == o.bill_phone &&
          bill_fax == o.bill_fax &&
          comment == o.comment &&
          admin_comment == o.admin_comment &&
          customer_first_name == o.customer_first_name &&
          customer_last_name == o.customer_last_name &&
          customer_birthday == o.customer_birthday &&
          customer_fax == o.customer_fax &&
          customer_phone == o.customer_phone &&
          shipp_address_2 == o.shipp_address_2 &&
          shipp_company == o.shipp_company &&
          shipp_phone == o.shipp_phone &&
          shipp_fax == o.shipp_fax &&
          date_modified == o.date_modified &&
          date_finished == o.date_finished &&
          subtotal_price == o.subtotal_price &&
          tax_price == o.tax_price &&
          shipping_price == o.shipping_price &&
          shipping_tax == o.shipping_tax &&
          discount == o.discount &&
          coupon_discount == o.coupon_discount &&
          gift_certificate_discount == o.gift_certificate_discount &&
          fulfillment_status == o.fulfillment_status &&
          financial_status == o.financial_status &&
          total_paid == o.total_paid &&
          external_source == o.external_source &&
          tags == o.tags &&
          inventory_behaviour == o.inventory_behaviour &&
          create_invoice == o.create_invoice &&
          order_item == o.order_item
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [order_id, store_id, order_status, send_notifications, send_admin_notifications, customer_email, bill_first_name, bill_last_name, bill_address_1, bill_city, bill_postcode, bill_state, bill_country, shipp_first_name, shipp_last_name, shipp_address_1, shipp_city, shipp_postcode, shipp_state, shipp_country, total_price, date, order_payment_method, order_shipping_method, currency, bill_address_2, bill_company, bill_phone, bill_fax, comment, admin_comment, customer_first_name, customer_last_name, customer_birthday, customer_fax, customer_phone, shipp_address_2, shipp_company, shipp_phone, shipp_fax, date_modified, date_finished, subtotal_price, tax_price, shipping_price, shipping_tax, discount, coupon_discount, gift_certificate_discount, fulfillment_status, financial_status, total_paid, external_source, tags, inventory_behaviour, create_invoice, order_item].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
